apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: alidar-dev-tls
spec:
  secretName: alidar-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: alidar.dev
  dnsNames:
    - alidar.dev
    - www.alidar.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - alidar.dev
          - www.alidar.dev
